# generated by Bing ai.
require 'sinatra'

get '/' do
  erb :index
end

post '/guestbook' do
  name = params[:name]
  message = params[:message]

  File.open('guestbook.txt', 'a') do |file|
    file.puts "#{name}: #{message}"
  end

  redirect '/'
end
